import os
from fpdf import FPDF

class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        
    def header(self):
        # Arial bold 15
        self.set_font("helvetica", "B", 15)
        # Move to the right
        self.cell(80)
        # Title
        self.cell(30, 10, "AutoStartup AI - Business Plan", border=0, align="C")
        # Line break
        self.ln(20)
        
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}", align="C")
        
    def chapter_title(self, title):
        # Arial 12
        self.set_font("helvetica", "B", 16)
        # Background color
        self.set_fill_color(230, 230, 245)
        self.set_text_color(79, 70, 229) # Indigo
        self.cell(0, 10, title, fill=True, align="L", border=0)
        self.ln(12)
        
    def chapter_body(self, body):
        # Times 12
        self.set_font("helvetica", "", 11)
        self.set_text_color(31, 41, 55) # Gray 800
        # Output text
        self.multi_cell(0, 7, body)
        self.ln()

def generate_business_plan_pdf(plan_data: dict, file_path: str, images: list = None, flowchart_path: str = None):
    """
    Generates a professional PDF document business plan.
    """
    if images is None:
        images = []
        
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    pdf = PDF()
    
    # 1. Title Page
    pdf.set_font("helvetica", "B", 28)
    pdf.set_text_color(31, 41, 55)
    pdf.ln(50)
    pdf.multi_cell(0, 15, plan_data.get('startup_title', 'Business Plan'), align="C")
    
    pdf.set_font("helvetica", "", 16)
    pdf.set_text_color(100, 100, 120)
    pdf.ln(10)
    pdf.multi_cell(0, 10, "Generated by AutoStartup AI", align="C")
    
    pdf.add_page()
    
    img_idx = 0
    def add_section(heading, content):
        nonlocal img_idx
        pdf.chapter_title(heading)
        
        # Add image if available
        if img_idx < len(images):
            try:
                # Add image centered, width 150mm
                pdf.image(images[img_idx], x="C", w=150)
                pdf.ln(5)
                img_idx += 1
            except Exception as e:
                print(f"Failed to add image to PDF: {e}")
                
        pdf.chapter_body(str(content) if content else 'N/A')

    # 2. Executive Summary
    add_section("Executive Summary", plan_data.get('executive_summary', 'N/A'))
    
    # 3. Problem Statement & Target Audience
    prob_target = f"Problem Statement:\n{plan_data.get('problem_statement', 'N/A')}\n\nTarget Audience:\n{plan_data.get('target_audience', 'N/A')}"
    add_section("The Problem & Target Audience", prob_target)
    
    # 4. Solution
    add_section("The Solution", plan_data.get('solution', 'N/A'))
    
    # 5. Core Features
    add_section("Core Features", plan_data.get('core_features', 'N/A'))
    
    # 6. Market Gap
    add_section("Market Gap & Opportunity", plan_data.get('market_gap', 'N/A'))
    
    # 7. Business & Revenue Model
    add_section("Business & Revenue Model", plan_data.get('revenue_model', 'N/A'))
    
    # 8. Implementation Roadmap
    add_section("Implementation Roadmap", plan_data.get('implementation_roadmap', 'N/A'))
    
    # 9. Architecture / System Blueprint (Flowchart)
    if flowchart_path and os.path.exists(flowchart_path):
        pdf.add_page()
        pdf.chapter_title("System Architecture / Blueprint")
        pdf.chapter_body("The following diagram illustrates the proposed system architecture and operational flow:")
        try:
            pdf.image(flowchart_path, x="C", w=160)
        except Exception as e:
            print(f"Failed to add flowchart to PDF: {e}")

    pdf.output(file_path)
