import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_business_plan_word(plan_data: dict, file_path: str, images: list = None, flowchart_path: str = None):
    """
    Generates a professional Word document business plan.
    """
    if images is None:
        images = []
        
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    doc = Document()
    
    # Define styles
    styles = doc.styles
    
    # Title style
    title_style = styles['Title']
    title_style.font.name = 'Arial'
    title_style.font.size = Pt(28)
    title_style.font.color.rgb = RGBColor(31, 41, 55)
    
    # Heading 1 style
    h1_style = styles['Heading 1']
    h1_style.font.name = 'Arial'
    h1_style.font.size = Pt(18)
    h1_style.font.color.rgb = RGBColor(79, 70, 229)
    
    # Normal text style
    normal_style = styles['Normal']
    normal_style.font.name = 'Arial'
    normal_style.font.size = Pt(11)
    
    # Helper to add section
    def add_section(heading, content, image_path=None):
        doc.add_heading(heading, level=1)
        if image_path and os.path.exists(image_path):
            doc.add_picture(image_path, width=Inches(6.0))
            last_paragraph = doc.paragraphs[-1] 
            last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph() # spacing
            
        p = doc.add_paragraph(str(content) if content else 'N/A')
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        doc.add_paragraph() # Extra spacing

    # 1. Title Page
    doc.add_heading(plan_data.get('startup_title', 'Business Plan'), 0)
    p = doc.add_paragraph("Generated by AutoStartup AI")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()
    
    # Keep track of available images to distribute them
    img_idx = 0
    def get_next_image():
        nonlocal img_idx
        if img_idx < len(images):
            path = images[img_idx]
            img_idx += 1
            return path
        return None

    # 2. Executive Summary
    add_section("Executive Summary", plan_data.get('executive_summary', 'N/A'), get_next_image())
    
    # 3. Problem Statement & Target Audience
    prob_target = f"Problem Statement:\n{plan_data.get('problem_statement', 'N/A')}\n\nTarget Audience:\n{plan_data.get('target_audience', 'N/A')}"
    add_section("The Problem & Target Audience", prob_target, get_next_image())
    
    # 4. Solution
    add_section("The Solution", plan_data.get('solution', 'N/A'), get_next_image())
    
    # 5. Core Features
    add_section("Core Features", plan_data.get('core_features', 'N/A'))
    
    # 6. Market Gap
    add_section("Market Gap & Opportunity", plan_data.get('market_gap', 'N/A'))
    
    # 7. Business & Revenue Model
    add_section("Business & Revenue Model", plan_data.get('revenue_model', 'N/A'))
    
    # 8. Implementation Roadmap
    add_section("Implementation Roadmap", plan_data.get('implementation_roadmap', 'N/A'))
    
    # 9. Architecture / System Blueprint (Flowchart)
    if flowchart_path and os.path.exists(flowchart_path):
        doc.add_page_break()
        doc.add_heading("System Architecture / Blueprint", level=1)
        doc.add_paragraph("The following diagram illustrates the proposed system architecture and operational flow:")
        doc.add_picture(flowchart_path, width=Inches(6.5))
        last_paragraph = doc.paragraphs[-1] 
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.save(file_path)
